name: string_manager_flutter
description:
  A Flutter Package for Managing App Strings in flutter applications on all platforms particularly
  internationalization.
version: 0.0.2
homepage: https://github.com/folaoluwafemi/string_manager_flutter

environment:
  sdk: ">=2.17.6 <3.0.5"
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.2.0

flutter: